# Generated by Django 4.2.3 on 2023-08-01 17:51

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_game_updated_at_devlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screenshot',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(default=list, to='main_app.tag'),
        ),
        migrations.AlterField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.file'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
