# Generated by Django 4.2.3 on 2023-08-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_screenshot_options_profile_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
    ]
