# Generated by Django 4.2.3 on 2023-08-02 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_game_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
