# Generated by Django 4.2.3 on 2023-08-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_devlog_date_alter_game_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='add_fullscreen_btn',
            field=models.BooleanField(default=True),
        ),
    ]
