# Generated by Django 4.2.3 on 2023-08-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_game_add_fullscreen_btn'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
