# Generated by Django 4.2.3 on 2023-08-04 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_url',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
