# Generated by Django 4.2.3 on 2023-08-04 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_file_url_file_key_alter_file_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.file'),
        ),
    ]
