# Generated by Django 4.2.3 on 2023-08-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_file_created_at'),
        ('main_app', '0010_alter_screenshot_file'),
    ]

    operations = [
    ]
