# Generated by Django 4.2.3 on 2023-08-04 19:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20230804_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, null=True, size=None),
        ),
    ]
