# Generated by Django 4.2.3 on 2023-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_profile_avatar_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
