# Generated by Django 4.2.3 on 2023-08-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_rename_created_at_review_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='url',
        ),
    ]
