# Generated by Django 4.2.3 on 2023-08-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
    ]
