# Generated by Django 4.2.3 on 2023-08-14 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0017_remove_file_mime_type_remove_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.game'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
